<?php

namespace Airsoft\GestionBundle\Entity;

/**
 * TresorierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TresorierRepository extends \Doctrine\ORM\EntityRepository
{
}
